add deployment task using az ml cli v2

diff --git a/.pipelines/yolov5-cd.yml b/.pipelines/yolov5-cd.yml
--- a/.pipelines/yolov5-cd.yml
+++ b/.pipelines/yolov5-cd.yml
@@ -26,14 +26,15 @@ resources:
 variables:
 - template: yolov5-variables-template.yml
 - group: yolov5-aml-vg
+- name: DEPLOYMENT_FILE
+  value: "online_deployment.yaml"
 
 stages:
-- stage: 'Deploy_ACI'
-  displayName: 'Deploy to ACI'
-  condition: variables['ACI_DEPLOYMENT_NAME']
+- stage: 'Deploy_Manage_Compute'
+  displayName: 'Deploy to AZ ML Managed Endpoint'
   jobs:
-  - job: "Deploy_ACI"
-    displayName: "Deploy to ACI"
+  - job: "Deploy_Manage_Compute"
+    displayName: "Deploy to AZ ML Managed Endpoint"
     container: mlops
     timeoutInMinutes: 0
     steps:
@@ -43,119 +44,119 @@ stages:
         projectId: '$(resources.pipeline.yolov5-Train-Eval-Reg-pipeline.projectID)'
         pipelineId: '$(resources.pipeline.yolov5-Train-Eval-Reg-pipeline.pipelineID)'
         artifactBuildId: ${{ parameters.artifactBuildId }}
-    - task: AzureCLI@1
-      displayName: 'Install AzureML CLI'
+    - task: AzureCLI@2
+      displayName: 'Install AzureML CLI v2'
       inputs:
         azureSubscription: '$(WORKSPACE_SVC_CONNECTION)'
         scriptLocation: inlineScript
         workingDirectory: $(Build.SourcesDirectory)
-        inlineScript: 'az extension add --source https://azurecliext.blob.core.windows.net/release/azure_cli_ml-1.27.0-py3-none-any.whl --yes'
-    - task: AzureCLI@1
-      displayName: "Deploy to ACI (CLI)"
+        inlineScript: 'az extension add -n ml'
+    - task: AzureCLI@2
+      displayName: "Deploy to AZ ML Managed Endpoint (CLI)"
+      condition: variables['ENDPOINT_NAME']
       inputs:
         azureSubscription: '$(WORKSPACE_SVC_CONNECTION)'
         scriptLocation: inlineScript
         workingDirectory: $(Build.SourcesDirectory)/$(SOURCES_DIR_TRAIN)
         inlineScript: |
           set -e # fail on error
-          
-          az ml model deploy --name $(ACI_DEPLOYMENT_NAME) --model '$(MODEL_NAME):$(get_model.MODEL_VERSION)' \
-          --ic ./scoring/inference_config.yml \
-          --dc ./scoring/deployment_config_aci.yml \
+          sed -i -e 's/$(MODEL_NAME)/$(MODEL_NAME):$(get_model.MODEL_VERSION)/g' $(DEPLOYMENT_FILE)
+          # Update az ml deployment
+          az ml online-deployment update -f $(DEPLOYMENT_FILE) \
+          -e $(ENDPOINT_NAME)  \
           -g $(RESOURCE_GROUP) --workspace-name $(WORKSPACE_NAME) \
-          --overwrite -v
-    - task: AzureCLI@1
-      displayName: 'Smoke test'
-      inputs:
-        azureSubscription: '$(WORKSPACE_SVC_CONNECTION)'
-        scriptLocation: inlineScript
-        inlineScript: |
-          set -e # fail on error
-          export SUBSCRIPTION_ID=$(az account show --query id -o tsv)
-          python -m ml_service.util.smoke_test_scoring_service --type ACI --service "$(ACI_DEPLOYMENT_NAME)"
+    # - task: AzureCLI@2
+    #   displayName: 'Smoke test'
+    #   inputs:
+    #     azureSubscription: '$(WORKSPACE_SVC_CONNECTION)'
+    #     scriptLocation: inlineScript
+    #     inlineScript: |
+    #       set -e # fail on error
+    #       export SUBSCRIPTION_ID=$(az account show --query id -o tsv)
+    #       python -m ml_service.util.smoke_test_scoring_service --type ACI --service "$(ACI_DEPLOYMENT_NAME)"
 
-- stage: 'Deploy_AKS'
-  displayName: 'Deploy to AKS'
-  dependsOn: Deploy_ACI
-  condition: and(succeeded(), variables['AKS_DEPLOYMENT_NAME'])
-  jobs:
-  - job: "Deploy_AKS"
-    displayName: "Deploy to AKS"
-    container: mlops
-    timeoutInMinutes: 0
-    steps:
-    - template: yolov5-get-model-id-artifact-template.yml
-      parameters:
-        projectId: '$(resources.pipeline.yolov5-Train-Eval-Reg-pipeline.projectID)'
-        pipelineId: '$(resources.pipeline.yolov5-Train-Eval-Reg-pipeline.pipelineID)'
-        artifactBuildId: ${{ parameters.artifactBuildId }}
-    - task: AzureCLI@1
-      displayName: 'Install AzureML CLI'
-      inputs:
-        azureSubscription: '$(WORKSPACE_SVC_CONNECTION)'
-        scriptLocation: inlineScript
-        workingDirectory: $(Build.SourcesDirectory)
-        inlineScript: 'az extension add --source https://azurecliext.blob.core.windows.net/release/azure_cli_ml-1.27.0-py3-none-any.whl --yes'
-    - task: AzureCLI@1
-      displayName: "Deploy to AKS (CLI)"
-      inputs:
-        azureSubscription: '$(WORKSPACE_SVC_CONNECTION)'
-        scriptLocation: inlineScript
-        workingDirectory: $(Build.SourcesDirectory)/$(SOURCES_DIR_TRAIN)
-        inlineScript: |
-          set -e # fail on error
+# - stage: 'Deploy_AKS'
+#   displayName: 'Deploy to AKS'
+#   dependsOn: Deploy_ACI
+#   condition: and(succeeded(), variables['AKS_DEPLOYMENT_NAME'])
+#   jobs:
+#   - job: "Deploy_AKS"
+#     displayName: "Deploy to AKS"
+#     container: mlops
+#     timeoutInMinutes: 0
+#     steps:
+#     - template: yolov5-get-model-id-artifact-template.yml
+#       parameters:
+#         projectId: '$(resources.pipeline.yolov5-Train-Eval-Reg-pipeline.projectID)'
+#         pipelineId: '$(resources.pipeline.yolov5-Train-Eval-Reg-pipeline.pipelineID)'
+#         artifactBuildId: ${{ parameters.artifactBuildId }}
+#     - task: AzureCLI@1
+#       displayName: 'Install AzureML CLI'
+#       inputs:
+#         azureSubscription: '$(WORKSPACE_SVC_CONNECTION)'
+#         scriptLocation: inlineScript
+#         workingDirectory: $(Build.SourcesDirectory)
+#         inlineScript: 'az extension add --source https://azurecliext.blob.core.windows.net/release/azure_cli_ml-1.27.0-py3-none-any.whl --yes'
+#     - task: AzureCLI@1
+#       displayName: "Deploy to AKS (CLI)"
+#       inputs:
+#         azureSubscription: '$(WORKSPACE_SVC_CONNECTION)'
+#         scriptLocation: inlineScript
+#         workingDirectory: $(Build.SourcesDirectory)/$(SOURCES_DIR_TRAIN)
+#         inlineScript: |
+#           set -e # fail on error
           
-          az ml model deploy --name $(AKS_DEPLOYMENT_NAME) --model '$(MODEL_NAME):$(get_model.MODEL_VERSION)' \
-          --compute-target $(AKS_COMPUTE_NAME) \
-          --ic ./scoring/inference_config.yml \
-          --dc ./scoring/adeployment_config_aks.yml \
-          -g $(RESOURCE_GROUP) --workspace-name $(WORKSPACE_NAME) \
-          --overwrite -v
-    - task: AzureCLI@1
-      displayName: 'Smoke test'
-      inputs:
-        azureSubscription: '$(WORKSPACE_SVC_CONNECTION)'
-        scriptLocation: inlineScript
-        inlineScript: |
-          set -e # fail on error
-          export SUBSCRIPTION_ID=$(az account show --query id -o tsv)
-          python -m ml_service.util.smoke_test_scoring_service --type AKS --service "$(AKS_DEPLOYMENT_NAME)"
+#           az ml model deploy --name $(AKS_DEPLOYMENT_NAME) --model '$(MODEL_NAME):$(get_model.MODEL_VERSION)' \
+#           --compute-target $(AKS_COMPUTE_NAME) \
+#           --ic ./scoring/inference_config.yml \
+#           --dc ./scoring/adeployment_config_aks.yml \
+#           -g $(RESOURCE_GROUP) --workspace-name $(WORKSPACE_NAME) \
+#           --overwrite -v
+#     - task: AzureCLI@1
+#       displayName: 'Smoke test'
+#       inputs:
+#         azureSubscription: '$(WORKSPACE_SVC_CONNECTION)'
+#         scriptLocation: inlineScript
+#         inlineScript: |
+#           set -e # fail on error
+#           export SUBSCRIPTION_ID=$(az account show --query id -o tsv)
+#           python -m ml_service.util.smoke_test_scoring_service --type AKS --service "$(AKS_DEPLOYMENT_NAME)"
 
-- stage: 'Deploy_Webapp'
-  displayName: 'Deploy to Webapp'
-  condition: variables['WEBAPP_DEPLOYMENT_NAME']
-  jobs:
-  - job: "Deploy_Webapp"
-    displayName: "Package and deploy model"
-    container: mlops
-    timeoutInMinutes: 0
-    steps:
-    - template: yolov5-get-model-id-artifact-template.yml
-      parameters:
-        projectId: '$(resources.pipeline.yolov5-Train-Eval-Reg-pipeline.projectID)'
-        pipelineId: '$(resources.pipeline.yolov5-Train-Eval-Reg-pipeline.pipelineID)'
-        artifactBuildId: ${{ parameters.artifactBuildId }}
-    - template: yolov5-package-model-template.yml
-      parameters:
-        modelId: $(MODEL_NAME):$(get_model.MODEL_VERSION)
-        scoringScriptPath: '$(Build.SourcesDirectory)/$(SOURCES_DIR_TRAIN)/scoring/score.py'
-        condaFilePath: '$(Build.SourcesDirectory)/$(SOURCES_DIR_TRAIN)/conda_dependencies.yml'
-    - script: echo $(IMAGE_LOCATION) >image_location.txt
-      displayName: "Write image location file"
-    - task: AzureWebAppContainer@1
-      name: WebAppDeploy
-      displayName: 'Azure Web App on Container Deploy'
-      inputs:
-        azureSubscription: '$(AZURE_RM_SVC_CONNECTION)'
-        appName: '$(WEBAPP_DEPLOYMENT_NAME)'
-        resourceGroupName: '$(RESOURCE_GROUP)'
-        imageName: '$(IMAGE_LOCATION)'
-    - task: AzureCLI@1
-      displayName: 'Smoke test'
-      inputs:
-        azureSubscription: '$(WORKSPACE_SVC_CONNECTION)'
-        scriptLocation: inlineScript
-        inlineScript: |
-          set -e # fail on error
-          export SUBSCRIPTION_ID=$(az account show --query id -o tsv)
-          python -m ml_service.util.smoke_test_scoring_service --type Webapp --service "$(WebAppDeploy.AppServiceApplicationUrl)/score"
+# - stage: 'Deploy_Webapp'
+#   displayName: 'Deploy to Webapp'
+#   condition: variables['WEBAPP_DEPLOYMENT_NAME']
+#   jobs:
+#   - job: "Deploy_Webapp"
+#     displayName: "Package and deploy model"
+#     container: mlops
+#     timeoutInMinutes: 0
+#     steps:
+#     - template: yolov5-get-model-id-artifact-template.yml
+#       parameters:
+#         projectId: '$(resources.pipeline.yolov5-Train-Eval-Reg-pipeline.projectID)'
+#         pipelineId: '$(resources.pipeline.yolov5-Train-Eval-Reg-pipeline.pipelineID)'
+#         artifactBuildId: ${{ parameters.artifactBuildId }}
+#     - template: yolov5-package-model-template.yml
+#       parameters:
+#         modelId: $(MODEL_NAME):$(get_model.MODEL_VERSION)
+#         scoringScriptPath: '$(Build.SourcesDirectory)/$(SOURCES_DIR_TRAIN)/scoring/score.py'
+#         condaFilePath: '$(Build.SourcesDirectory)/$(SOURCES_DIR_TRAIN)/conda_dependencies.yml'
+#     - script: echo $(IMAGE_LOCATION) >image_location.txt
+#       displayName: "Write image location file"
+#     - task: AzureWebAppContainer@1
+#       name: WebAppDeploy
+#       displayName: 'Azure Web App on Container Deploy'
+#       inputs:
+#         azureSubscription: '$(AZURE_RM_SVC_CONNECTION)'
+#         appName: '$(WEBAPP_DEPLOYMENT_NAME)'
+#         resourceGroupName: '$(RESOURCE_GROUP)'
+#         imageName: '$(IMAGE_LOCATION)'
+#     - task: AzureCLI@1
+#       displayName: 'Smoke test'
+#       inputs:
+#         azureSubscription: '$(WORKSPACE_SVC_CONNECTION)'
+#         scriptLocation: inlineScript
+#         inlineScript: |
+#           set -e # fail on error
+#           export SUBSCRIPTION_ID=$(az account show --query id -o tsv)
+#           python -m ml_service.util.smoke_test_scoring_service --type Webapp --service "$(WebAppDeploy.AppServiceApplicationUrl)/score"
